@startuml
'https://plantuml.com/activity-diagram-beta
while (queue.isEmpty()) is (not empty)
    :queue.getMin();
    if(executionTime <= currentTime) then(true)
        :queue.wait();
        i

endwhile


':queue.isEmpty();
':new page;
'if (Page.onSecurityCheck) then (true)
'  :Page.onInit();
'  if (isForward?) then (no)
'    :Process controls;
'    if (continue processing?) then (no)
'      stop
'    endif
'
'    if (isPost?) then (yes)
'      :Page.onPost();
'    else (no)
'      :Page.onGet();
'    endif
'    :Page.onRender();
'  endif
'else (false)
'endif

'if (do redirect?) then (yes)
'  :redirect process;
'else
'  if (do forward?) then (yes)
'    :Forward request;
'  else (no)
'    :Render page template;
'  endif
'endif
'
':ClickServlet;
':task;




stop

@enduml
